import pyaudio

# AUDIO CONFIGURATION

INPUT_SAMPLE_RATE = 22050
INPUT_SAMPLE_PER_FRAME = 1024
INPUT_CHANNELS = 1
INPUT_FORMAT = pyaudio.paInt16

OUTPUT_SAMPLE_RATE = 44100
OUTPUT_SAMPLE_PER_FRAME = 1024
OUTPUT_CHANNELS = 2
OUTPUT_FORMAT = pyaudio.paInt16

MIN_VOLUME = 10000

# NOTES IDs

# Considering C0 = 0
MIN_NOTE_ID = 28		# E2
MAX_NOTE_ID = 62		# D5

# NOTES

MIN_NOTE_FREQUENCY = 82.406876		# E2 (Hz)

# MUSICS MAP

BASE_NOTES_ARRAY = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']

